name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Docker
      uses: docker/setup-buildx-actions@v2

    - name: Login to Docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      run: |
       docker build -t ${{secrets.DOCKER_USERNAME}}/tenant-app .
       docker push ${{secrets.DOCKER_USERNAME}}/tenant-app 
    
    - name: Run the container
      uses: container/run-action@v2
      run: |
        docker run -d -p 5000:5000 ${{secrets.DOCKER_USERNAME}}/tenant-app
    
    - name: Logout from Docker
      run: docker logout
    
